spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:watchlist_db}
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: "${REDIS_HOST:localhost}"
      port: "${REDIS_PORT:6379}"
      password: "${REDIS_PASSWORD}"
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${MAIL_USERNAME}"
    password: "${MAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  frontend-url: "${FRONTEND_URL}"
  verification-token-expiration-minutes: 1440   # 24 saat
  reset-token-expiration-minutes: 15

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

admin:
  username: ${ADMIN_USERNAME}
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

tmdb:
  api:
    key: ${TMDB_API_KEY}
    base-url: https://api.themoviedb.org/3

  
